### ISSUE TITLE
티켓 확인 및 마이페이지 메뉴 구현

### ISSUE THREAD

**Issue by tigowler** [Likelion-at-SMWU-10th/Trobber#9]
## 📌 To-do
- [ ] 마이페이지 탭 슬라이드 구현
- [ ] 사용자 이름, 이메일 등 기본 레이아웃 구현
- [ ] 티켓 컴포넌트 구현 완료
